FROM biocorecrg/debian-perlbrew-pyenv3-java:buster

# File Author / Maintainer
MAINTAINER Toni Hermoso Pulido <toni.hermoso@crg.eu> 

ARG IPSCAN_VERSION=5.48-83.0
ARG IPSCAN_DATA=/nfs/db/iprscan/5.48-83.0

# Install InterPro

RUN cd /usr/local; curl --retry 3 --fail --silent --show-error --location --remote-name https://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/${IPSCAN_VERSION}/interproscan-${IPSCAN_VERSION}-64-bit.tar.gz && \
	curl --retry 3 --fail --silent --show-error --location --remote-name https://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/${IPSCAN_VERSION}/interproscan-${IPSCAN_VERSION}-64-bit.tar.gz.md5 && \
	md5sum -c interproscan-${IPSCAN_VERSION}-64-bit.tar.gz.md5

RUN cd /usr/local; tar zxf interproscan-${IPSCAN_VERSION}-64-bit.tar.gz --exclude "interproscan-${IPSCAN_VERSION}/data" && rm interproscan-${IPSCAN_VERSION}-64-bit.tar.gz interproscan-${IPSCAN_VERSION}-64-bit.tar.gz.md5

ENV PATH "/usr/local/interproscan-${IPSCAN_VERSION}:${PATH}"

# Replace interproscan.properties

COPY interproscan.open.properties /usr/local/interproscan-${IPSCAN_VERSION}/interproscan.properties
RUN chmod a+r /usr/local/interproscan-${IPSCAN_VERSION}/interproscan.properties

RUN ln -s /usr/local/interproscan-${IPSCAN_VERSION} /usr/local/interproscan

# Hardcoded Data
VOLUME ${IPSCAN_DATA}
RUN cd /usr/local/interproscan; rm -rf data; ln -s ${IPSCAN_DATA} data

# Extra packages
RUN apt-get update; apt-get install -y libdw1

# Clean cache
RUN apt-get clean
RUN set -x; rm -rf /var/lib/apt/lists/*
