FROM biocorecrg/debian-perlbrew-pyenv3-java:buster AS builder

ARG IPSCAN_VERSION=5.52-86.0

# Install InterPro

RUN cd /usr/local; curl --retry 3 --fail --silent --show-error --location --remote-name https://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/${IPSCAN_VERSION}/interproscan-${IPSCAN_VERSION}-64-bit.tar.gz && \
	curl --retry 3 --fail --silent --show-error --location --remote-name https://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/${IPSCAN_VERSION}/interproscan-${IPSCAN_VERSION}-64-bit.tar.gz.md5 && \
	md5sum -c interproscan-${IPSCAN_VERSION}-64-bit.tar.gz.md5

RUN cd /usr/local; tar zxf interproscan-${IPSCAN_VERSION}-64-bit.tar.gz --exclude "interproscan-${IPSCAN_VERSION}/data" && rm interproscan-${IPSCAN_VERSION}-64-bit.tar.gz interproscan-${IPSCAN_VERSION}-64-bit.tar.gz.md5

# Replace interproscan.properties
COPY interproscan.properties /usr/local/interproscan-${IPSCAN_VERSION}/interproscan.properties
RUN chmod a+r /usr/local/interproscan-${IPSCAN_VERSION}/interproscan.properties
RUN chmod -R a+rx /usr/local/interproscan-${IPSCAN_VERSION}/bin/* 

RUN cd /usr/local/interproscan-${IPSCAN_VERSION}; rm -rf data

FROM biocorecrg/debian-perlbrew-pyenv3-java:buster

# File Author / Maintainer
MAINTAINER Toni Hermoso Pulido <toni.hermoso@crg.eu> 

ARG IPSCAN_VERSION=5.52-86.0

ENV PATH "/usr/local/interproscan:${PATH}"

COPY --from=builder /usr/local/interproscan-${IPSCAN_VERSION} /usr/local/interproscan

WORKDIR /usr/local/interproscan

# Extra packages
RUN apt-get update; apt-get install -y libdw1 libpcre3
RUN cd /lib/x86_64-linux-gnu; ln -s libpcre.so.3 libpcre.so

# Clean cache
RUN apt-get clean
RUN set -x; rm -rf /var/lib/apt/lists/*
